config/routes.rb
Agreatfirstdate::Application.routes.draw do
  apipie

  namespace :api do

    # Version 1
    namespace :v1 do
      # post   'users/sign_in' => 'sessions#create'
      # delete 'users/sign_out'=> 'sessions#destroy'

      devise_scope :user do
        # get "sign_in", :to => "sessions#new"
        post "sign_in", :to => "sessions#create"
        # get "sign_up", :to => "registrations#new"
        # post "sign_up", :to => "registrations#create"
        get "sign_out", :to => "sessions#destroy"
        # get "password/new", :to => "passwords#new"
      end

      resources :profiles, only: [:show] do
        collection do
          get 'me'
          put 'me' => 'profiles#me_update'
        end
      end
      resources :pillars, only: :show
      resources :events, only: [:create, :show, :update, :destroy]
    end

    resources :instagram, only: [:index] do
      collection do
        get :media
      end
    end
    resource :permissions, only: [:index]
    namespace :facebook do
      resources :albums, only: [:index, :show]
    end

    resources :strikes, only: [:create]
    resources :favorites, only: [ :index, :create, :destroy ]

    resources :users
    resources :searches, only: [:index] do
      get 'opposite_sex' => 'searches#opposite_sex', on: :collection
    end
    resources :profiles do
      collection do
        post 'send_email'
        get 'avatars' => 'avatars#index'
        post 'avatars' => 'avatars#create'
        delete 'avatars/:id' => 'avatars#destroy'
        put "avatars/:id" => "avatars#update"
      end
      member do
        put :deactivate
        get :activate
      end
    end
    resources :event_items, only: [:create, :update, :destroy]
    resources :pillars do
      resources :event_types, only: [:index]
    end
    resources :event_photos
    resource :pillar_categories, only: [:update]
    get '/geo_lookup' => 'geo_lookup#index'
    get '/discount' => 'discount#index'
    get '/me' => 'profiles#me'
    put '/me' => 'profiles#update'
    resource :billing, :only => [:show, :update, :destroy], :controller => "billing"

  end

  root :to => 'welcome#index'

  resources :profiles, :only => [:show] do
    post 'send_email', on: :member
    put 'activate', on: :member
    put 'deactivate', on: :member
    put 'still_inappropriate', on: :member
  end

  get '/me'                 => 'my_profile#show',           :as => :my_profile
  get '/me/points'          => 'my_profile#points',         :as => :my_points
  get '/me/edit'            => 'my_profile#edit',           :as => :edit_profile
  get '/me/geo'             => 'my_profile#geo',            :as => :geo_profile
  put '/me'                 => 'my_profile#update',         :as => :update_profile
  put '/me/cancel'          => 'my_profile#cancel',         :as => :cancel_account
  post '/me/select_pillars' => 'my_profile#select_pillars', :as => :select_pillars
  get '/me/facebook_albums' => 'my_profile#facebook_albums'
  get '/me/instagram_photos' => 'my_profile#instagram_photos'
  get '/me/facebook_album/:aid' => 'my_profile#facebook_album'

  devise_for :users,
    controllers: {
      sessions: 'sessions',
      registrations: 'registrations',
      omniauth_callbacks: 'omniauth_callbacks'
    }

  devise_scope :user do
    get '/users/auth/:provider' => 'omniauth_callbacks#passthru'
    get '/users/confirm_email' => 'registrations#confirm_email'
    post '/users/confirm_email' => 'registrations#confirm_email'
  end

  post '/store_settings' => 'users#store_settings', as: :store_settings

  get 'blog' => 'blog#index'
  get 'blog/:alias' => 'blog#show', as: :blog_post
  resources :posts, only: [:new, :edit, :update, :create, :destroy]

  get "welcome/index"
  get "welcome/about"
  get "welcome/blog"
  get "welcome/faq"
  get "welcome/privacy"
  get "welcome/terms"
  post "welcome/send_feedback"

  resources :pillars do
    resources :event_types, only: :index, on: :member do
      resources :event_descriptors, only: :index, on: :member
    end
    resources :event_items, only: [:index, :create, :update], on: :member
  end

  resources :event_items do
    put 'activate', on: :member
    put 'deactivate', on: :member
    put 'still_inappropriate', on: :member
  end

  resources :event_photos

  resources :searches, only: [:index]

  resources :event_types do
    resources :event_descriptors, only: :index, on: :member
  end

  resources :inappropriate_contents, only: [] do
    put :fix, on: :member
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    redirect_to my_profile_path if user_signed_in?
  end

  def faq
    respond_to do |format|
      format.html{}
      format.js{ render :layout => false }
    end

  end

  def send_feedback
    @feedback = Feedback.new(params[:feedback].keep_keys([:email, :subject, :body]).merge(user: current_user))
    if @feedback.save
      render json: @feedback
    else
      render json: {errors: @feedback.errors}, status: :unprocessable_entity
    end
  end
end

app/views/welcome/about.html.haml
.pages
	%h1 About Us

	%p aGreatFirstDate.com, Ltd. was founded in Denver, Colorado in late 2011.  We have a simple mission: get people on better dates.  What does that mean exactly?  Great dates happen when you are out with someone who is attractive, and with whom you have something to talk about.  The site was designed to bring out those two qualities in each and every member.

	%h1 Our Story

	%p We thought online dating should be easier. We thought it should be more natural. We wanted it to work for the people around us.  Rory tried it a couple of times with no success. His friends have tried it.  His sister has tried it.  Tim's Mom tried it. The whole thing was just so... unnatural.  So we returned to first principles. We asked ourselves, how do we connect with people that we don't know? The answer is surprisingly simple: common interests and shared experiences. This is how Rory met his wife. This is how it works. This is what A Great! First Date is meant to be.

	%p 
		We're a small startup, intent on focusing entirely on great user experiences and putting the customer first.  We accomplish those goals by using the latest technology and talking to our customers every chance we get.  If you are interested in joining our team and helping us build great dates, send us an e-mail:
		= link_to "careers@agreatfirstdate.com", "mailto:careers@agreatfirstdate.com"

	%p We are currently in a public beta program restricted to the Denver/Boulder area.

app/views/welcome/blog.html.haml
%h1 The Blog

app/views/welcome/faq.html.haml
.pages
  %h1 Frequently Asked Questions

  %dl
    %dt Q.  I want to sign up.  How come my city isn’t on the list!
    %dd A.  We are working our way through the major cities across the US.  This site is about great dates, and dating long distance is a hard thing to do.  Please leave your name and city on the form and will do our best to come to your city as soon as we can.

    %dt Q. What’s with the point system?
    %dd A. The point system helps us keep the whole process moving along.  You get points for keeping your profile updated, and you can use those points to contact more interesting first dates.  We want people on this site to feel safe and comfortable, so we have no intention of letting anyone spam anyone else.  Points help us do that.

    %dt Q.  How do I get points?
    %dd
      A.  We reserve the right to tweak the point system as necessary, but currently it works like this:

      %ul
        %li 100 points for signing in
        %li 100 points for adding your 4 pillars
        %li 100 points every week?
        %li 500 points for referring a friend (v2?)
        %li 50 points for being contacted
        %li 25 points for adding an timeline event up to 4 per day
        %li 10 points for each day you login up to 3 per day
        %li 3 points every time you get favorited
        %li 1 point every time someone views your page

      Contacting someone costs you 100 points.

    %dt Q. How do the strikes work?  Sometimes the profiles come back quickly, sometimes they don’t.
    %dd A.  Once you give someone a strike, they won’t return in your searches until two things happen.  First, they have to make a change to their profile.  Second, you have to do another search at least a day later.

    %dt Q.  Ok, so why do you do that?
    %dd A.  We believe that dating is process.  The whole site is built around that idea.  People sometimes upload pictures that aren’t very flattering.  Sometimes people take up new or interesting hobbies, or decide to share their hidden passion for pottery.  We want to encourage you to be patient and to get to know people as much as possible.

    %dt Q.  How come I can only search within my pillars?
    %dd A.  Our objective is to get you out into the real world on dates that will be great.  While it is possible to fall for someone that you have nothing in common with, we think those relationships are unlikely to be successful, or at least the first date stands a good chance of being boring.

    %dt Q.  If I find myself in a candle emergency, what do I do?
    %dd A.  Place a piece of string in a can of Crisco, it will burn for 45 days. For lesser needs, place a crayon upright and it will burn for 30 minutes.

    %dt Q.  What’s with the direct e-mails?
    %dd A.  We believe the Internet is a fairly public place these days.  We give you one layer of anonymity and then trust you to make the right decision for you after that.  There are also plenty of great e-mail management tools out there.  Using Gmail you can filter and report inappropriate e-mails.  If you still aren’t comfortable, we suggest creating an new e-mail account just for use on this site.

    %dt Q.  And the same is true of the first name and last initial on the profile?
    %dd A.  Yes, we expect our members to be high caliber singles looking to find the same.  When we meet someone in real life we don’t give a silly name like “supercook39.”  We introduce ourselves with our real names and hope that something great happens.  This isn’t 1995.  We expect people to use the Internet, and our site, responsibly.  Plus if you don’t, remember we’ve got your real name. (kidding)

    %dt Q.  I’m both very picky and verbose, how come I can’t add more text in the About Me and Who I’d Like to Meet Section?
    %dd A.  We want you to meet someone in the context of what they do with their lives, not what they have to say about their lives.  We want people to meet you the same way.  We want you to have great dates, not endless conversations about politics, deal breakers, and your entire relationship history before you ever get face to face with someone.

    %dt Q.  Fine.  I assume the same is true for the profile pictures?  I had eight different head shots taken so I could look really, really good online.
    %dd A.  Yep, you only get three profile pictures.  All the other pictures have to happen in the context of your pillars.  If you are really, really good looking, we suggest you add the “Fashion / Modeling” pillar and add them there.

app/views/welcome/index.html.haml
- seo :title => t('seo.title_homepage'), :description => t('seo.description_homepage')
#slides
  %ul.slides-container
    %li.home
      = image_tag 'bg-home.jpg', :class => "slide-image"
      .container.gallery-slide
        .inner
          .hero
            %h1 Timeline Based Profiles
            %p By using timeline based profiles, A Great! First Date gives you the truest picture of how a person is in real life.  No more pictures from five years ago, no more awkward conversations, just interesting people doing interesting things.
          .row
            .reg_page
              .video_block
                %iframe{:allowFullScreen => "", :frameborder => "0", :height => "348", :mozallowfullscreen => "", :src => "//player.vimeo.com/video/53564984?title=0&byline=0&portrait=0", :webkitAllowFullScreen => "", :width => "619"}

              = simple_form_for(User.new, :as => :user, :url => registration_path(:user) , :html => { :class => "reg_form"}) do |f|
                = link_to omniauth_authorize_path(:user, :facebook), :class => "btn btn-large fb_btn popup", :"data-width" => 600, :"data-height" => 400 do
                  %i.fa.fa-facebook.fa-lg 
                  Sign Up with Facebook
                %span.or
                = f.input_field :first_name, :required => true, :label => false, :placeholder => 'First name'
                = f.input_field :email, :required => true, :label => false, :placeholder => 'E-mail'
                = f.error :email, :class => "error"
                = f.input_field :password, :required => true, :label => false, :placeholder => 'Password'
                = f.error :password, :class => "error"

                %p
                  By clicking "Sign Up with Facebook" or Sign up you are agreeing to the
                  = link_to_terms_of_use
                  and consent to our
                  = link_to_privacy_policy

                = f.button :submit, "Sign Up", :class => "btn-info btn-large sign_up_btn"

    %li.how_it_works
      = image_tag 'bg-how-it-works.jpg', :class => "slide-image"
      .container.gallery-slide
        .row
          .span12
            .inner
              .profile-info
                %p.name Alex, 26 years old
                %p.categories (Travel, Eat, Family, Fitness)
                %p.description — It’s exciting to finally find a dating site that reflect how we are actually living our daily lives.

              .info
                %h2 How it works
                %ul
                  %li Pick the four pillars of you.
                  %li Update them with the things you do.
                  %li Match with people who like you for it.
                  %li Go on great first dates.
                  %li It’s simple and it’s real.

    %li.get_started
      = image_tag 'bg-get-started.jpg', :class => "slide-image"
      .container.gallery-slide
        .row
          .span12
            .inner
              .profile-info
                %p.name Scott, 27 years old
                %p.categories (Fashion, Health, Music, Movie)
                %p.description — aGreatFirstDate.com is a totally unique online experience for meeting new people. It`s the one dating site that allows me to show who I am, where I`ve been and where I`m going.

              = simple_form_for :profile,url: searches_path, method: :get,  html: {class: 'today_form'} do |f|
                %h3 Get started today!
                %fieldset
                  %label I’m a
                  = select_tag :gender, options_for_select(Profile::GENDERS.map{|g, title|[title.humanize, g]}, 'man'), class: 'gender_select'

                %fieldset
                  %label I’m looking for
                  = select_tag :looking_for, options_for_select( Profile::GENDERS.map{|g, title|[title.humanize.pluralize, g]}, 'female'), class: 'gender_select'

                %fieldset
                  %label In or arround
                  = select_tag :in_or_around, options_for_select(['Denver, CO']), class: 'gender_select'
                %fieldset
                  %label Roughly this age
                  = select_tag :looking_for_age, options_for_select(['25-35', '35-45', '45-55']), class: 'gender_select'

                %input.btn.btn-large.send{:type => "submit", :value => "Browse"}/
                / END today_form

  %nav.slides-navigation
    %a.next{:href => '#'}
      %i.icon-home-right
    %a.prev{:href => '#'}
      %i.icon-home-left

app/views/welcome/privacy.html.haml
.pages
  %h1.center
    aGreatFirstDate.com
    %br
    Privacy Policy

  %p aGreatFirstDate.com, Ltd., a Colorado limited liability company  (“GFD,” “we”, “us”) respects your privacy. This Privacy policy informs you of our privacy practices and of the choices you can make about the way your information is collected online and how that information is used.  If you have questions or concerns regarding this statement please contact us at: #{link_to "admin@agreatfirstdate.com", "mailto:admin@agreatfirstdate.com"}.

  %p By accessing  and  using this website or other services owned or operated by GFD (collectively, the services), you agree to the terms and conditions of this privacy policy. If you do not agree please do not use the services.

  %h2 Collection of personal information:

  %p To serve you better and understand your needs and interests, GFD collects, exports and uses your personal information. For example, when you register on our site, order products or services, request information, participate in surveys, or post information, we will ask for personal information to complete these transactions. The personal information you provide to us may include contact information such as your name, age, gender, address, telephone number, financial information such as a credit card number; and other unique information such as user ID’s and passwords, billing and transaction information, product and service preferences and contact preferences. 

  %p If you post, comment or share personal information, including photographs, to your public profile, forum, social network or blog please be aware that any personal information may be read, viewed, collected, or used by other users of the GFD's site, and could be used to contact you and send unsolicited messages, or for other purposes.  We encourage you to exercise discretion and caution before posting your personal information.

  %p In addition to the information you provide, GFD may also collect information during your visit to our site by means of automatic data collection tools, which include web beacons, cookies, embedded web links and other commonly used information gathering tools. Such tools collect standard information that your browser sends to our website such as your browser type, language, access times and the address of the website form which you arrived at the GFD website.  They may also collect information Protocol  (IP) address, behavior (i.e. the pages you view, the links you click and other actions you take in connection with the GFD website). 

  %p An IP address is a number that is automatically assigned to your computer whenever you are on the Web, allowing Web servers to locate and indentify your computer. Computers use IP addresses to communicate on the Internet, allowing users to browse, communicate and otherwise be susceptible to identity theft.

  %p GFD may use some of the collection tools in connection with certain emails sent from GFD and therefore may collect information in the email.  

  %h2 How we use your information:

  %p The information collected by GFD is used to understand your needs and interests which helps us deliver a consistent, personalized and enjoyable experience.  GFD may use your information to:

  %ul
    %li Prevent and detect fraud or other malicious activity;
    %li Assist you in completing a transaction;
    %li Communicate with you about products and services;
    %li Provide service and support;
    %li Update you on new matches;
    %li Provide personalized offers.

  %p Credit card information is used only for payment processing. Credit card information required to process a credit card decision is not used for any other purpose and will not be kept longer than necessary for providing the service, unless you request that we retain the information for future transactions.

  %h2 How we share your information:  

  %p GFD will not sell, rent or lease your personal information to others except as described in the statement. GFD shares personal information in the following ways:

  %p GFD retains service providers and suppliers to deliver products, services, marketing and customer solutions. Service providers may include credit card processors, customer support, email service providers, data processors and shipping agents. All providers are required by contract to keep confidential information received on behalf of GFD and may not use it for any purpose other than to complete the services for which they have been contracted.

  %p GFD may participate in marketing initiatives with other companies. These initiatives may include certain services and marketing communications at the same time as other companies. Some of these services and communications offer you the option to share personal information with both GFD and the other companies participating in these initiatives. For example, you may receive marketing communications from us and other companies or have the opportunity to register online for products and services from multiple companies. If you choose to provide personal information with the other companies participating in that marketing initiative that personal information will be handled according to the privacy policy of those companies.

  %p GFD may also share your personal information with the businesses with which we partner to offer you personalized services, products, or advertisements.  When you elect to participate in a business partners' offer or program, you authorize GFD to provide your email address and other personal information to that business partner.  Please contact us at #{link_to "admin@agreatfirstdate.com", "mailto:admin@agreatfirstdate.com"} to learn how to opt-out of cookies that my be utilized by third party data or advertising partners. 

  %p Except as described in this privacy policy, GFD will not share the information you provide to us with third parties without your permission, unless to: (i) respond to duly authorized information requests from police and governmental authorities: (ii) comply with any law, regulation, subpoena, or court order; (iii) help prevent fraud or to enforce or protect the rights and properties of GFD; or (iv) protect the personal safety of GFD employees.

  %p Circumstances may arise where for business reasons, GFD decides to sell, buy, merge or otherwise reorganize businesses. Such a transaction may involve disclosure of personal information to prospective or actual purchasers, or the receipt of it from sellers. It is GFD practice to seek appropriate protection for information in these types of transactions.

  %h2 Links to third party sites:

  %p The GFD website may provide links to third-party websites for your convenience. If you access those links, you will leave the GFD  website.  GFD does not control those sites or their privacy practices. We do not endorse or make any representations regarding third party sites. The personal data you choose to share with third parties is not covered by the GFD privacy policy . We recommend that you familiarize yourself with the privacy policies of any such third party site.

  %h2 Children’s privacy:

  %p GFD does not knowingly collect information from children under the age of 18 and does not target its website to children under the age of 18. We encourage parents and guardians to take an active role in their children’s online activities and interests.

  %h2 Your choices and selecting your privacy preferences:

  %p GFD gives you the choice of receiving a variety of information that complements our services. You can subscribe to receive certain products and service information and also choose to receive general communications by postal service, email or telephone.

  %p You can make or change your choices about receiving either subscription or general communications at the data collection point or by using other methods, which are listed in the following sections. This option does not apply to communications primarily for the purpose of administering order completion, contracts, support, updates or other administrative and transactional notices as the primary purpose of these communications is not promotional in nature.

  %p The email communications that you receive from us will be provided in accordance with this statement. Some email communications may utilize automatic data collection tools. 

  %h2 Subscription Communications:

  %p Subscription communications include email newsletters, software updates, etc. that may be expressly requested by you or which you consented to receive. After you request such communications, you may opt out of receiving them by using one of the following methods:

  %ul
    %li Select the email “opt out” or “unsubscribe” link, or follow the opt-out instructions included with each subscription communication.
    %li Return to the Web page where you originally registered your preferences and follow the opt-out instructions.
    %li Write to GFD at #{link_to "admin@agreatfirstdate.com", "mailto:admin@agreatfirstdate.com"}. Be sure to provide your name, email and postal address, and specific relevant information about GFD subscriptions that you no longer wish to receive.
    %li Please be aware that when you opt out of receiving communications, it may affect the services you have chosen to receive from us where accepting the communications is a condition for receiving services.

  %h2 General communications:

  %p General communications provide information about products, services, and/or support. This may include new information of new services, special offers, or invitations to participate in market research.

  %p You will be able to indicate whether you want to receive general communications from us by writing to GFD at #{link_to "admin@agreatfirstdate.com", "mailto:admin@agreatfirstdate.com"}.  Be sure to provide your name, email and postal address, and specific relevant information about your privacy preferences.

  %h2 Access to and accuracy of your information:

  %p GFD strives to keep your personal information accurately recorded. We have implemented policies to help maintain data accuracy. GFD provides individuals with reasonable access to their personal information and the ability to review and correct it or ask for deletion, as applicable. To protect your privacy and security, we will also take reasonable steps to verify your identity, such as requiring a password and user ID, before granting access to your data. To view and change the personal information that you directly provided to us you can return to the Web page where you originally submitted your data and follow the instructions on that web page, or contact GFD at #{link_to "admin@agreatfirstdate.com", "mailto:admin@agreatfirstdate.com"}.

  %h2 Keeping your personal information secure:

  %p GFD takes seriously the trust you place in us. To prevent unauthorized access or disclosure, to maintain data accuracy, and to ensure the appropriate use of the information, GFD utilizes reasonable procedures to safeguard the information we collect.  The personal information you provide us is stored on computer systems, which have limited access. When we transmit highly confidential information (such as credit or password) over the Internet, we protect it through the use of encryption. Credit card numbers are used only for processing payments and are not used for other purposes.  However, no system can be completely secure.  Therefore, we cannot guarantee, and you cannot expect, that your personal information, searches or other communications will always remain secure.

  %h2 Changes to this policy:

  %p If we change our privacy policy, we will post the revised policy here. We reserve the right, at our sole discretion, to change this Privacy Policy from time to time. Your continued use of GFD's Website after such changes take effect will be deemed to constitute your acceptance of and agreement to the new Privacy Policy. 


  %h2 Contacting Us:

  %p We value your opinions. If you have comments or questions about our privacy policy, please send them to #{link_to "admin@agreatfirstdate.com", "mailto:admin@agreatfirstdate.com"} or write to us at the following address:

  %p
    aGreatFirstDate.com, Ltd.
    %br
    3815 Jason Street
    %br
    Denver, CO 80211
    
  %p Last updated: May 16, 2012