config/routes.rb
Agreatfirstdate::Application.routes.draw do
  apipie

  namespace :api do

    # Version 1
    namespace :v1 do
      # post   'users/sign_in' => 'sessions#create'
      # delete 'users/sign_out'=> 'sessions#destroy'

      devise_scope :user do
        # get "sign_in", :to => "sessions#new"
        post "sign_in", :to => "sessions#create"
        # get "sign_up", :to => "registrations#new"
        # post "sign_up", :to => "registrations#create"
        get "sign_out", :to => "sessions#destroy"
        # get "password/new", :to => "passwords#new"
      end

      resources :profiles, only: [:show] do
        collection do
          get 'me'
          put 'me' => 'profiles#me_update'
        end
      end
      resources :pillars, only: :show
      resources :events, only: [:create, :show, :update, :destroy]
    end

    resources :instagram, only: [:index] do
      collection do
        get :media
      end
    end
    resource :permissions, only: [:index]
    namespace :facebook do
      resources :albums, only: [:index, :show]
    end

    resources :strikes, only: [:create]
    resources :favorites, only: [ :index, :create, :destroy ]

    resources :users
    resources :searches, only: [:index] do
      get 'opposite_sex' => 'searches#opposite_sex', on: :collection
    end
    resources :profiles do
      collection do
        post 'send_email'
        get 'avatars' => 'avatars#index'
        post 'avatars' => 'avatars#create'
        delete 'avatars/:id' => 'avatars#destroy'
        put "avatars/:id" => "avatars#update"
      end
      member do
        put :deactivate
        get :activate
      end
    end
    resources :event_items, only: [:create, :update, :destroy]
    resources :pillars do
      resources :event_types, only: [:index]
    end
    resources :event_photos
    resource :pillar_categories, only: [:update]
    get '/geo_lookup' => 'geo_lookup#index'
    get '/discount' => 'discount#index'
    get '/me' => 'profiles#me'
    put '/me' => 'profiles#update'
    resource :billing, :only => [:show, :update, :destroy], :controller => "billing"

  end

  root :to => 'welcome#index'

  resources :profiles, :only => [:show] do
    post 'send_email', on: :member
    put 'activate', on: :member
    put 'deactivate', on: :member
    put 'still_inappropriate', on: :member
  end

  get '/me'                 => 'my_profile#show',           :as => :my_profile
  get '/me/points'          => 'my_profile#points',         :as => :my_points
  get '/me/edit'            => 'my_profile#edit',           :as => :edit_profile
  get '/me/geo'             => 'my_profile#geo',            :as => :geo_profile
  put '/me'                 => 'my_profile#update',         :as => :update_profile
  put '/me/cancel'          => 'my_profile#cancel',         :as => :cancel_account
  post '/me/select_pillars' => 'my_profile#select_pillars', :as => :select_pillars
  get '/me/facebook_albums' => 'my_profile#facebook_albums'
  get '/me/instagram_photos' => 'my_profile#instagram_photos'
  get '/me/facebook_album/:aid' => 'my_profile#facebook_album'

  devise_for :users,
    controllers: {
      sessions: 'sessions',
      registrations: 'registrations',
      omniauth_callbacks: 'omniauth_callbacks'
    }

  devise_scope :user do
    get '/users/auth/:provider' => 'omniauth_callbacks#passthru'
    get '/users/confirm_email' => 'registrations#confirm_email'
    post '/users/confirm_email' => 'registrations#confirm_email'
  end

  post '/store_settings' => 'users#store_settings', as: :store_settings

  get 'blog' => 'blog#index'
  get 'blog/:alias' => 'blog#show', as: :blog_post
  resources :posts, only: [:new, :edit, :update, :create, :destroy]

  get "welcome/index"
  get "welcome/about"
  get "welcome/blog"
  get "welcome/faq"
  get "welcome/privacy"
  get "welcome/terms"
  post "welcome/send_feedback"

  resources :pillars do
    resources :event_types, only: :index, on: :member do
      resources :event_descriptors, only: :index, on: :member
    end
    resources :event_items, only: [:index, :create, :update], on: :member
  end

  resources :event_items do
    put 'activate', on: :member
    put 'deactivate', on: :member
    put 'still_inappropriate', on: :member
  end

  resources :event_photos

  resources :searches, only: [:index]

  resources :event_types do
    resources :event_descriptors, only: :index, on: :member
  end

  resources :inappropriate_contents, only: [] do
    put :fix, on: :member
  end
end

app/controllers/my_profile_controller.rb
class MyProfileController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_profile_data, :only => :show
  respond_to :html, :json

  def select_pillars
    if profile.set_active_pillars params[:user_pillar][:selected_pillar_ids]
      render json: {pillars: profile.reload.pillars.map {|p| p.serializable_hash(scope: :self) }}
    else
      render :status => 404, :json => profile.errors[:pillars]
    end
  end

  def points
    render json: {points: profile.points}
  end

  def geo
    geo = GeoKit::Geocoders::MultiGeocoder.multi_geocoder "zip #{params[:zip]}"
    if geo.success && geo.state && geo.city
      render :json =>  {:state => geo.state, :city => geo.city}
    else
      render :json => {}, :status => 404
    end
  end

  def show
    @pillars = profile.pillars
    @pillar_categories = PillarCategory.all
    respond_to do |format|
      format.html { render 'profiles/show' }
      format.json { render json: profile, scope: :self }
    end
  end

  def edit
    @pillars = profile.pillars
    @pillar_categories = PillarCategory.all
  end

  def cancel
    profile.cancel!
    respond_to do |format|
      format.html { redirect_to my_profile_path, notice: 'Profile was successfully updated.' }
      format.json { render json: profile, scope: :self }
      format.js {  } # avatar upload
    end
  end

  def update
    respond_to do |format|
      if params[:profile][:user_attributes]
        user_attributes = params[:profile][:user_attributes].clone.keep_keys([:email, :current_password, :password, :password_confirmation])
        params[:profile][:user_attributes] = params[:profile][:user_attributes].keep_keys([:id])
      end
      @state = profile.update_attributes(params[:profile].keep_keys(Profile::ACCESSIBLE_ATTRIBUTES))
      unless !user_attributes || user_attributes[:current_password].blank?
        @state &&= profile.user.update_with_password(user_attributes)
      end

      if @state
        profile.reload
        format.html { redirect_to my_profile_path, notice: 'Profile was successfully updated.' }
        format.json { render json: profile, scope: :self }
        format.js {  } # avatar upload
      else
        profile.reload_card_attributes!
        format.html { render action: "edit" }
        format.json { render json: profile.errors, status: :unprocessable_entity }
        format.js { }
      end
    end
  end

  def facebook_albums
    render json: current_user.facebook_albums if current_user.facebook_token
  end

  def instagram_photos
    opt = {}
    opt[:max_id] = params[:max_id] if params[:max_id]
    render json: current_user.instagram_photos(opt) if current_user.instagram_token
  end

  def facebook_album
    aid = params[:aid].scan(/aid([0-9]+)/)[0][0]

    render json: current_user.facebook_album(aid) if current_user.facebook_token
  end
end

app/views/my_profile/_profile_edit_form.html.haml
#event_items_popup
#settings

  .row.profile_edit
    .span12.well
      %h3.expanded My Settings
      .row
        = simple_form_for profile, :url => update_profile_path, html: {class: 'form-horizontal', id: 'edit_profile'} do |f|
          .span6
            = f.fields_for :user do |f|
              = f.input :email, :input_html =>{:class => "input-large"}
            = f.input :first_name, :input_html =>{:class => "input-large"}
            = f.input :last_name, :input_html =>{:class => "input-large"}
            = f.input :birthday,
              :start_year => Date.today.year - 80,
              :end_year => Date.today.year - 16,
              :include_blank => true,
              :order => [:month, :day, :year]
          .span6
            .row
              = f.input :gender, collection: Profile::GENDERS.map{|g, title|[title.humanize, g]}, prompt: true
              = f.input :looking_for, collection: Profile::GENDERS.map{|g, title|[title.humanize.pluralize, g]}, prompt: true
              = f.input :in_or_around, collection: Profile::LOCATIONS, include_blank: false
              = f.input :looking_for_age do
                .age-controls
                  = f.label :looking_for_age_from
                  = f.text_field :looking_for_age_from, :class => 'span1'
                  = f.label :looking_for_age_to
                  = f.text_field :looking_for_age_to, :class => 'span1'
            .row
              .pull-right{:style => "margin-right:40px;"}
                = f.button :submit, (f.object.new_profile? ? 'Save & Create Profile' : 'Save'), :class => " btn-large"

  .row.profile_edit
    .span12.well
      %a{ name: 'billing' }
      %h3.collapsed.billing Billing Info
      .row.nested-row.hide
        = simple_form_for profile, :url => api_billing_path, method: :put, html: {class: 'form-horizontal', id: 'edit_billing_profile'} do |f|
          .row.profile_edit
            .span8{:style => "color: #8dc63f;"}
              #billing-update-flash
          .row.profile_edit
            .span6
              = f.input :billing_full_name, :input_html => { :class => 'input-xlarge' }, :label => "Full Name"
              = f.input :address1, :input_html => { :class => 'input-xlarge' }
              = f.input :address2, :input_html => { :class => 'input-xlarge' }
              = f.input :city
              = f.input :state
              = f.input :zip, :input_html => { :class => 'input-small' }, :wrapper_html => {:class => "zip-spin"}
              = f.input :country, as: :select, collection: Country::NAMES
            .span5
              #manage-card-actions{style: ('display: none;' unless f.object.stripe_customer_token.present?)}
                .row
                  .span1
                  .span5#card-stub
                    .span1.pull-left
                      = image_tag "cards/#{ f.object.card_type_to_image_name }.png", id: 'js-card-type',
                        data: { :visa               => image_path('cards/visa.png'),
                                :mastercard         => image_path('cards/mastercard.png'),
                                :'american-express' => image_path('cards/american-express.png'),
                                :discover           => image_path('cards/discover.png'),
                                :'diners-club'      => image_path('cards/diners-club.png'),
                                :jcb                => image_path('cards/jcb.png') }
                    #masked-card-info.pull-left
                      %p.card-number= "**** **** **** #{f.object.card_last4}"
                      %p.ending-in= "Ending in: #{f.object.card_exp_month}/#{f.object.card_exp_year}"
                    .clearfix
                .row
                  .span1
                  .span3#card-actions
                    .span2
                      = link_to "Edit", "#", id: 'js-edit-credit-card'
                      \|
                      = link_to "Delete", "#",id: "delete-credit-card"

              #card-info{style: ('display: none;' if f.object.stripe_customer_token.present?)}
                .control-group.string.optional
                  %label.string.optional.control-label
                    = label_tag :card_number, 'Credit Card Number'
                  .controls
                    = text_field_tag :card_number, nil, name: nil
                .control-group.string.optional
                  %label.string.optional.control-label
                    Expiration
                  .controls.controls-row
                    = select_month Date.today, {use_month_numbers: true}, {name: nil, id: "card_exp_month", style: 'width:60px;'}
                    = select_year Date.today, {start_year: Date.today.year, end_year: (Date.today+12.years).year}, {name: nil, id: 'card_exp_year', style: 'width: 100px'}
                .control-group.string.optional
                  %label.string.optional.control-label
                    CVC code
                  .controls
                    = text_field_tag :card_cvc, nil, name: nil, class: 'input-small'
                = f.input :discount_code, class: "input-medium", autocomplete: :off, :hint => " ", :wrapper_html => {:id => "discount-block"}
                .control-group
                  %label
                    Order Total
                  .controls
                    .string#total-amount{:style => "margin-top: 4px;"}
                      = number_to_currency 20



          .row.profile_edit{:style => "padding:10px;"}
            .span8
              %p{:style => "font-size:87%;"}
                By clicking Join Now you agree to the
                = link_to "terms of use", welcome_terms_path, target: '_blank'
                of this site.  You will be billed the amount shown today and you will be automatically charged each successive month according to the terms of your subscription. Automatic billing will continue until you cancel your membership from this page.
            .span3.pull-right#billing-button-place
              %button.btn.btn-large#join-now
                - if f.object.stripe_customer_token.present?
                  Update Billing Account
                - else
                  Join Now!

  .row.profile_edit
    .span12.well
      %h3.collapsed Change Password
      .row.nested-row.hide
        = simple_form_for profile, :url => update_profile_path, html: {class: 'form-horizontal', id: 'change_password'} do |f|
          = f.fields_for :user do |f|
            = f.input :current_password, as: :password, required: false
            = f.input :password, as: :password, required: false
            = f.input :password_confirmation, as: :password, required: false
          .offset4{:style => "margin-left: 324px;"}
            = f.button :submit, 'Save', :class => " btn-large"



  .row.profile_edit
    .span12.well
      %h3.collapsed Change Pillars
      .row.nested-row.hide
        .control-group
          .row
            %p.span5 You can only change pillars once a month for free. After once a month it costs you 300 points.
          .row
            .span5
              = link_to "Change Pillars", "#pillars/choose"

  .row.profile_edit
    .span12.well
      %h3.collapsed Cancel My Account
      .row.nested-row.hide
        %br
        %button.btn.btn-large#cancel-account
          Cancel


#event_items_popup.modal.hide.fade
#show_event_items_popup.modal.hide.fade
#profile_popup.modal.hide.fade
#choose_pillars_popup.modal.hide.fade
#facebook_albums_popup.modal.hide.fade

- content_for :javascript_includes do
  = javascript_include_tag "https://js.stripe.com/v2/"

- content_for :javascript do
  $(function() {
  new Agreatfirstdate.Routers.UserSettingRouter()
  - if @profile == current_user.profile
    profile =  #{ raw(@profile.to_json(scope: :self)) }
    userRouter = new Agreatfirstdate.Routers.UserRouter({profile: #{ raw(@profile.to_json(scope: :self)) }});
  - else
    profile =  #{ raw(@profile.to_json(scope: :profile)) }
    userRouter = new Agreatfirstdate.Routers.UserRouter({profile: #{ raw(@profile.to_json(scope: :profile)) } });



  userSetting = new Agreatfirstdate.Views.User.Settings({el: $("#settings")})

  pillarsRouter = new Agreatfirstdate.Routers.PillarsRouter({profile: profile, pillars: #{ raw(@pillars.to_json scope: :self) }, pillarCategories: #{ raw(@pillar_categories.to_json(scope: :self)) }});
  })

app/views/my_profile/edit.html.haml
= render 'profile_edit_form'

app/views/my_profile/update.js.erb
<%= remotipart_response do %>
  var model = window.userRouter.user;
  <% if @state %>
    model.avatars.reset(<%= @profile.avatars.to_json(scope: :self).html_safe %>);
    model.set('points', '<%= @profile.points %>');
  <% else %>
    model.trigger('error', model, <%= @profile.errors.to_json.html_safe %>);
  <% end %>
<% end %>