config/routes.rb
Agreatfirstdate::Application.routes.draw do
  apipie

  namespace :api do

    # Version 1
    namespace :v1 do
      # post   'users/sign_in' => 'sessions#create'
      # delete 'users/sign_out'=> 'sessions#destroy'

      devise_scope :user do
        # get "sign_in", :to => "sessions#new"
        post "sign_in", :to => "sessions#create"
        # get "sign_up", :to => "registrations#new"
        # post "sign_up", :to => "registrations#create"
        get "sign_out", :to => "sessions#destroy"
        # get "password/new", :to => "passwords#new"
      end

      resources :profiles, only: [:show] do
        collection do
          get 'me'
          put 'me' => 'profiles#me_update'
        end
      end
      resources :pillars, only: :show
      resources :events, only: [:create, :show, :update, :destroy]
    end

    resources :instagram, only: [:index] do
      collection do
        get :media
      end
    end
    resource :permissions, only: [:index]
    namespace :facebook do
      resources :albums, only: [:index, :show]
    end

    resources :strikes, only: [:create]
    resources :favorites, only: [ :index, :create, :destroy ]

    resources :users
    resources :searches, only: [:index] do
      get 'opposite_sex' => 'searches#opposite_sex', on: :collection
    end
    resources :profiles do
      collection do
        post 'send_email'
        get 'avatars' => 'avatars#index'
        post 'avatars' => 'avatars#create'
        delete 'avatars/:id' => 'avatars#destroy'
        put "avatars/:id" => "avatars#update"
      end
      member do
        put :deactivate
        get :activate
      end
    end
    resources :event_items, only: [:create, :update, :destroy]
    resources :pillars do
      resources :event_types, only: [:index]
    end
    resources :event_photos
    resource :pillar_categories, only: [:update]
    get '/geo_lookup' => 'geo_lookup#index'
    get '/discount' => 'discount#index'
    get '/me' => 'profiles#me'
    put '/me' => 'profiles#update'
    resource :billing, :only => [:show, :update, :destroy], :controller => "billing"

  end

  root :to => 'welcome#index'

  resources :profiles, :only => [:show] do
    post 'send_email', on: :member
    put 'activate', on: :member
    put 'deactivate', on: :member
    put 'still_inappropriate', on: :member
  end

  get '/me'                 => 'my_profile#show',           :as => :my_profile
  get '/me/points'          => 'my_profile#points',         :as => :my_points
  get '/me/edit'            => 'my_profile#edit',           :as => :edit_profile
  get '/me/geo'             => 'my_profile#geo',            :as => :geo_profile
  put '/me'                 => 'my_profile#update',         :as => :update_profile
  put '/me/cancel'          => 'my_profile#cancel',         :as => :cancel_account
  post '/me/select_pillars' => 'my_profile#select_pillars', :as => :select_pillars
  get '/me/facebook_albums' => 'my_profile#facebook_albums'
  get '/me/instagram_photos' => 'my_profile#instagram_photos'
  get '/me/facebook_album/:aid' => 'my_profile#facebook_album'

  devise_for :users,
    controllers: {
      sessions: 'sessions',
      registrations: 'registrations',
      omniauth_callbacks: 'omniauth_callbacks'
    }

  devise_scope :user do
    get '/users/auth/:provider' => 'omniauth_callbacks#passthru'
    get '/users/confirm_email' => 'registrations#confirm_email'
    post '/users/confirm_email' => 'registrations#confirm_email'
  end

  post '/store_settings' => 'users#store_settings', as: :store_settings

  get 'blog' => 'blog#index'
  get 'blog/:alias' => 'blog#show', as: :blog_post
  resources :posts, only: [:new, :edit, :update, :create, :destroy]

  get "welcome/index"
  get "welcome/about"
  get "welcome/blog"
  get "welcome/faq"
  get "welcome/privacy"
  get "welcome/terms"
  post "welcome/send_feedback"

  resources :pillars do
    resources :event_types, only: :index, on: :member do
      resources :event_descriptors, only: :index, on: :member
    end
    resources :event_items, only: [:index, :create, :update], on: :member
  end

  resources :event_items do
    put 'activate', on: :member
    put 'deactivate', on: :member
    put 'still_inappropriate', on: :member
  end

  resources :event_photos

  resources :searches, only: [:index]

  resources :event_types do
    resources :event_descriptors, only: :index, on: :member
  end

  resources :inappropriate_contents, only: [] do
    put :fix, on: :member
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_filter :find_post_by_alias, only: [:show, :edit]
  def index
    @posts = Post.recent.paginate(:page => params[:page])
  end
  
  def show

  end
  
private
  def find_post_by_alias
    @post = Post.find_by_alias(params[:alias])
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/_comments.html.haml
#comments
  %h2#comments-title
    One thought on “
    %span>= post.title
    \”
  %ol.commentlist
    - post.comments.each do |comment|
      %li#comment-2.comment.even.thread-even.depth-1
        #div-comment-2.comment-body
          .comment-author.vcard
            %img.avatar.avatar-32.photo{:alt => "", :height => "32", :src => "http://0.gravatar.com/avatar/47f653e4c735512d54a905bf6651affe?s=32&d=http%3A%2F%2F0.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D32&r=G", :width => "32"}/
            %cite.fn= comment.full_name
            %span.says says:
          .comment-meta.commentmetadata
            %a{:href => "http://blog.agreatfirstdate.com/a-great-first-date/#comment-2"}>
              May 14, 2012 at 9:39 pm
            \  
            %a.comment-edit-link{:href => "http://blog.agreatfirstdate.com/wp-admin/comment.php?action=editcomment&c=2", :title => "Edit comment"} (Edit)
          %p= comment.body
          .reply

app/views/blog/_linksalpha.html.erb
<div class="linksalpha-email-button" data-fs="row1=%23ffffff&row2=%23F5FCFC&row3=%23EEF9FD&row4=%23D8E6EB&twitterlang=en&title=FOLLOW+AND+SUSBCRIBE&t_size=10&width=255&t_color=%23555555&fs_url=http%3A%2F%2Fagreatfirstdate.com&gpluslang=en-US" id="linksalpha_tag_299138368" data-url="http://agreatfirstdate.com" data-text="" data-desc="" data-image="" ></div>
<script type="text/javascript" src="http://www.linksalpha.com/social/loader_fs?tag_id=linksalpha_tag_299138368&row1=%23ffffff&row2=%23F5FCFC&row3=%23EEF9FD&row4=%23D8E6EB&twitterlang=en&title=FOLLOW+AND+SUSBCRIBE&t_size=10&t_color=%23555555&fs_url=http%3A%2F%2Fagreatfirstdate.com&gpluslang=en-US"></script>

app/views/blog/_post.html.haml
.post.type-post.status-publish.format-standard.hentry
  .entry-meta
    .date
      = link_to post.published_at.strftime("%b %d %Y"), "http://blog.agreatfirstdate.com/a-great-first-date/" # "May 14 2012"
    -# .comments
    -#   = link_to "1 Comment", "http://blog.agreatfirstdate.com/a-great-first-date/#comments", :title => 'Comment on A Great! First Date'
    -# %span.cat-links
    -#   = link_to "Online Dating", "http://blog.agreatfirstdate.com/category/online-dating/", :title => "View all posts in Online Dating"
    - if user_signed_in? && current_user.admin?
      %span.edit-link
        = link_to "Edit", edit_post_path(post), :class => 'post-edit-link', :title => 'Edit Post'
      %span.edit-link
        = link_to 'Delete', post_path(post), :confirm => 'Are you sure?', :method => :delete
  .main
    %h2.entry-title
      = link_to post.title, blog_post_path(post.alias)
    .entry-content= raw(post.body)

app/views/blog/_share.html.erb
<div class="linksalpha-email-button" id="linksalpha_tag_526862710" data-url="<%= url %>" data-text="" data-desc="" data-image="" ></div>
<script type="text/javascript" src="http://www.linksalpha.com/social/loader_icons?tag_id=linksalpha_tag_526862710&prepends=14&vkontakte=1&twitter=1&popup=aolmail%2Cxing%2Cfoursquare%2Csonico%2Cnetlog%2Chotmail%2Csnipit%2Cmsn%2Cidentica%2Cposterous%2Clivejournal%2Cyammer%2Cyahoomail%2Cmyspace%2Cweibo%2Chyves%2Cmailru%2Cdiigo%2Creddit%2Cdelicious%2Cgmail%2Cevernote%2Cprint%2Cdigg%2Ctumblr%2Creaditlater%2Cvkontakte%2Cinstapaper&xinglang=de&linkedin=1&tumblr=1&prependc=7F7F7F&delicious=1&hyves=1&gpluslang=en-US&size=24&weibo=1&posterous=1&evernote=1&sonico=1&twitterlang=en&pinterest=1&myspace=1&prepend=Share+this+post+on%3A&msn=1&foursquare=1&print=1&gmail=1&mailru=1&email=1&reddit=1&hotmail=1&snipit=1&netlog=1&fontstyle=arial&twitterrelated=linksalpha&aolmail=1&facebook=1&diigo=1&xing=1&digg=1&yahoomail=1&yammer=1&stumbleupon=1&instapaper=1&googleplus=1&livejournal=1&readitlater=1&4sqid=&link=<%=u url %>&fblikelang=en_US&page=facebook%2Cemail%2Ctwitter%2Cstumbleupon%2Cgoogleplus%2Clinkedin%2Cpinterest&identica=1"></script>

app/views/blog/index.html.haml
.blog_container
  - if user_signed_in? && current_user.admin?
    = link_to 'Create post', new_post_path, :class => 'btn'
  #contents
    - @posts.each do |post|
      = render :partial => 'post', :locals => {:post => post}
  = will_paginate @posts, :renderer => WpLinkRenderer

app/views/blog/show.html.haml
.blog_container
  #contents
    = render :partial => 'post', :locals => {:post => @post}
    = render :partial => 'share', :locals => {:url => blog_post_url(@post.alias)}
    -# = render :partial => 'comments', :locals => {:post => @post}
  #widgets
    #widget-area
      = render :partial => 'linksalpha'
  