config/routes.rb
Agreatfirstdate::Application.routes.draw do
  apipie

  namespace :api do

    # Version 1
    namespace :v1 do
      # post   'users/sign_in' => 'sessions#create'
      # delete 'users/sign_out'=> 'sessions#destroy'

      devise_scope :user do
        # get "sign_in", :to => "sessions#new"
        post "sign_in", :to => "sessions#create"
        # get "sign_up", :to => "registrations#new"
        # post "sign_up", :to => "registrations#create"
        get "sign_out", :to => "sessions#destroy"
        # get "password/new", :to => "passwords#new"
      end

      resources :profiles, only: [:show] do
        collection do
          get 'me'
          put 'me' => 'profiles#me_update'
        end
      end
      resources :pillars, only: :show
      resources :events, only: [:create, :show, :update, :destroy]
    end

    resources :instagram, only: [:index] do
      collection do
        get :media
      end
    end
    resource :permissions, only: [:index]
    namespace :facebook do
      resources :albums, only: [:index, :show]
    end

    resources :strikes, only: [:create]
    resources :favorites, only: [ :index, :create, :destroy ]

    resources :users
    resources :searches, only: [:index] do
      get 'opposite_sex' => 'searches#opposite_sex', on: :collection
    end
    resources :profiles do
      collection do
        post 'send_email'
        get 'avatars' => 'avatars#index'
        post 'avatars' => 'avatars#create'
        delete 'avatars/:id' => 'avatars#destroy'
        put "avatars/:id" => "avatars#update"
      end
      member do
        put :deactivate
        get :activate
      end
    end
    resources :event_items, only: [:create, :update, :destroy]
    resources :pillars do
      resources :event_types, only: [:index]
    end
    resources :event_photos
    resource :pillar_categories, only: [:update]
    get '/geo_lookup' => 'geo_lookup#index'
    get '/discount' => 'discount#index'
    get '/me' => 'profiles#me'
    put '/me' => 'profiles#update'
    resource :billing, :only => [:show, :update, :destroy], :controller => "billing"

  end

  root :to => 'welcome#index'

  resources :profiles, :only => [:show] do
    post 'send_email', on: :member
    put 'activate', on: :member
    put 'deactivate', on: :member
    put 'still_inappropriate', on: :member
  end

  get '/me'                 => 'my_profile#show',           :as => :my_profile
  get '/me/points'          => 'my_profile#points',         :as => :my_points
  get '/me/edit'            => 'my_profile#edit',           :as => :edit_profile
  get '/me/geo'             => 'my_profile#geo',            :as => :geo_profile
  put '/me'                 => 'my_profile#update',         :as => :update_profile
  put '/me/cancel'          => 'my_profile#cancel',         :as => :cancel_account
  post '/me/select_pillars' => 'my_profile#select_pillars', :as => :select_pillars
  get '/me/facebook_albums' => 'my_profile#facebook_albums'
  get '/me/instagram_photos' => 'my_profile#instagram_photos'
  get '/me/facebook_album/:aid' => 'my_profile#facebook_album'

  devise_for :users,
    controllers: {
      sessions: 'sessions',
      registrations: 'registrations',
      omniauth_callbacks: 'omniauth_callbacks'
    }

  devise_scope :user do
    get '/users/auth/:provider' => 'omniauth_callbacks#passthru'
    get '/users/confirm_email' => 'registrations#confirm_email'
    post '/users/confirm_email' => 'registrations#confirm_email'
  end

  post '/store_settings' => 'users#store_settings', as: :store_settings

  get 'blog' => 'blog#index'
  get 'blog/:alias' => 'blog#show', as: :blog_post
  resources :posts, only: [:new, :edit, :update, :create, :destroy]

  get "welcome/index"
  get "welcome/about"
  get "welcome/blog"
  get "welcome/faq"
  get "welcome/privacy"
  get "welcome/terms"
  post "welcome/send_feedback"

  resources :pillars do
    resources :event_types, only: :index, on: :member do
      resources :event_descriptors, only: :index, on: :member
    end
    resources :event_items, only: [:index, :create, :update], on: :member
  end

  resources :event_items do
    put 'activate', on: :member
    put 'deactivate', on: :member
    put 'still_inappropriate', on: :member
  end

  resources :event_photos

  resources :searches, only: [:index]

  resources :event_types do
    resources :event_descriptors, only: :index, on: :member
  end

  resources :inappropriate_contents, only: [] do
    put :fix, on: :member
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :profile
  helper_method :current_profile

  before_filter :set_current_user

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to searches_path, alert: exception.message
  end

  def current_profile
    current_user.try(:profile)
  end

  protected
  def authenticate_admin!
    unless authenticate_user! && current_user.admin?
      flash[:error] = "unauthorized access"
      redirect_to root_path
    end
  end

  def check_profile_data
    if profile.invalid?
      flash.notice = "Give us some basic information, then create your profile. You'll be searching in less than 2 minutes!"
      redirect_to edit_profile_path
    end
  end

  def profile
    @profile ||= current_user.try :profile
  end

  def render_404
    render 'pages/404', :status => 404
  end

  def set_current_user
    User.current_user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def set_current_user_in_javascript
    return unless user_signed_in?
    user = UserPresenter.new(current_user).to_json
    profile = ProfilePresenter.new(current_user.profile).to_json scope: :self

    content_tag(:script) do
      <<-JS.html_safe
        window.current_user_attributes = #{ user };
        window.current_profile_attributes = #{ profile };
      JS
    end
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def profile
    current_user.profile
  end

  def card_status(profile)
    if profile.stripe_customer_token.present?
      'Verified!'
    else
      if profile.stripe_customer_token.blank?
        'Customer not active.'
      elsif !profile.customer_subscription_status
        'Customer ends subscription.'
      elsif !profile.invoice_status
        'Invoice attempts to be paid, and the payment fails.'
      end
    end
  end

  def seo(data = {})
    content_for :title, data[:title]
    content_for :description, data[:description]
    content_for :keywords, data[:keywords]
  end

  def seo_description
    if content_for? :description
      content_for(:description)
    end
  end

  def seo_title
    if content_for? :title
      content_for(:title)
    else
      t 'seo.title'
    end
  end

  def link_to_privacy_policy
    link_to 'privacy policy', welcome_privacy_path, :target => "_blank"
  end

  def link_to_terms_of_use
    link_to 'terms of use', welcome_terms_path, :target => "_blank"
  end

  def display_user_points
    points = current_user.profile.points

    # Makes points tickable after third sign in in the day
    if current_user.third_sign_in_today? && allow_tick_sign_in_points?
      points -= Point::EVENT_TYPES['Session']
      session[:sign_in_points_ticked] = true
    end

    content_tag :span, "#{ points } Points", id: :my_points
  end

  def allow_tick_sign_in_points?
    !session[:sign_in_points_ticked]
  end
end

app/views/application/_footer.html.haml
%footer#home-footer
  .container
    .inner
      .row
        %nav
          %ul#footer-nav
            %li= link_to 'The Blog', blog_path
            %li="|"
            %li= link_to 'FAQ', welcome_faq_path
            %li="|"
            %li= link_to 'Privacy', welcome_privacy_path
            %li="|"
            %li= link_to 'About', welcome_about_path
            %li="|"
            %li= link_to 'Terms of Use', welcome_terms_path
            %li="|"
            %li &copy; 2013 aGreatFirstDate.com
          = link_to "http://tech.co/a-great-first-date-the-anti-dating-site-dating-site-2012-12/", :target => "_blank" do
            = image_tag 'logos_tech_cocktail.png', :class => 'logos'

          = link_to "http://blogs.westword.com/latestword/2012/07/a_great_first_date_online_dating.php/", :target => "_blank" do
            = image_tag 'logos_westword.png', :class => 'logos'

          = link_to "http://303magazine.com/2012/08/showmances-a-great-first-date/", :target => "_blank" do
            = image_tag 'logos_303.png', :class => 'logos'

app/views/application/_homepage_video.html.erb
<%#= asset_path 'homepage-video_screenshot.jpg' %>
<%= videojs_rails sources: { mp4: "http://s3.amazonaws.com/agreatfirstdatecom/a_great_first_date_launch_video_1280x720.mp4" }, width: "400" %>

app/views/application/_login_box.html.haml
- unless user_signed_in?
  #welcomeLogin
    #welcomeLoginBox
      .devise-block
        %h3
          Already a
          %span member
          ?
        = simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f|
          = f.input :email, :required => false, :label => false, :placeholder => 'USERNAME', error: false
          = f.input :password, :required => false, :label => false, :placeholder => 'PASSWORD', error: false
          = f.input :remember_me, :as => :boolean, :required => false, :label => 'Remember me'
          = f.button :submit, "Welcome back"
          = link_to "Forgot your password?", new_password_path(resource_name), :class => "forgot_link"

      .facebook-block
        = link_to omniauth_authorize_path(resource_name, :facebook) do
          %i.facebook-signin-button

app/views/application/_top_nav_bar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to image_tag('agreatfirstdate.png'), root_path, :class => 'brand'
      .container
        .pull-right
          - if user_signed_in?
            #headerUserPoints.pull-right.btn
              = display_user_points

            %ul.nav.menu
              %li= link_to "Browse Profiles", searches_path
              %li="|"
              %li= link_to "My Profile", root_path
              %li="|"
              %li= link_to "Settings", edit_profile_path
              %li="|"
              %li= link_to "Sign out", destroy_user_session_path, :method => :delete

          - else
            - unless controller_name[/searches/]
              %ul.nav.menu
                - if current_page?('/')
                  %li= link_to_function "The Story", "showSlide(0)", :class => 'slider-link-0'
                  %li="|"
                  %li= link_to_function "How It Works", "showSlide(1)", :class => 'slider-link-1'
                  %li="|"
                  %li= link_to_function "Get Started", "showSlide(2)", :class => 'slider-link-2'
                - else
                  %li= link_to "The Story", "/"
                  %li="|"
                  %li= link_to "How It Works", "/"
                  %li="|"
                  %li= link_to "Get Started", "/"
            %ul.auth_block.pull-left
              %li.dropdown
                = link_to 'Sign Up', '#', class: 'btn dropdown-toggle', :data => {:toggle => "dropdown"}
                %ul.dropdown-menu.dropdown-form.sign_in_form
                  %li.dropdown-caret.right
                    %span.caret-outer
                    %span.caret-inner
                  %li
                    = simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name) , :html => { :class => "quick-reg"}) do |f|
                      = link_to omniauth_authorize_path(resource_name, :facebook), :class => "btn btn-large fb_btn popup" do
                        %i.fa.fa-facebook.fa-lg 
                        Sign Up with Facebook
                      %span.or
                      = f.input_field :first_name, :required => true, :label => false, :placeholder => 'First name'
                      = f.input_field :email, :required => true, :label => false, :placeholder => 'E-mail'
                      = f.error :email, :class => "error"
                      = f.input_field :password, :required => true, :label => false, :placeholder => 'Password'
                      = f.error :password, :class => "error"
                      -# = f.input_field :password_confirmation, :required => true, :label => false, :placeholder => 'Password confirmation'
                      -# = f.error :password_confirmation, :class => "error"
                      %p
                        By clicking "Sign Up with Facebook" or Sign Up you are agreeing to the
                        = link_to_terms_of_use
                        and consent to our
                        = link_to_privacy_policy

                      = f.button :submit, "Sign Up", :class => "btn-info btn-large sign_up_btn"
              %li.dropdown
                = link_to 'Log In', '#', class: 'btn dropdown-toggle', :data => {:toggle => "dropdown"}
                %ul.dropdown-menu.dropdown-form.sign_in_form
                  %li.dropdown-caret.right
                    %span.caret-outer
                    %span.caret-inner
                  %li
                    = simple_form_for resource, as: resource_name, url: session_path(resource_name), html: { class: 'quick-login' } do |f|
                      = link_to omniauth_authorize_path(resource_name, :facebook), :class => "btn btn-large fb_btn popup", :"data-width" => 600, :"data-height" => 400 do
                        %i.fa.fa-facebook.fa-lg 
                        Log In with Facebook
                      %span.or
                      .inputs
                        = f.input :email, :required => true, :autofocus => true, :placeholder => "E-mail", :label => false
                        = f.input :password, :required => true, :placeholder => "Password", :label => false
                        - if devise_mapping.rememberable?
                          .control-group.boolean.optional
                            .controls
                              = f.check_box :remember_me
                              %label.checkbox.remember{:style => "display:inline;padding:0px;", :for => "user_remember_me"}
                                Remember me
                              = f.button :submit, "Log In", :style => "margin-top:-2px;float:right;"

                      .bottom_links
                        = link_to "Forgot your password?", new_password_path(resource_name)                   